export default function SacrificeSacrificeSacrifice() {
  return (
    <div style={{
      fontFamily: "var(--body)",
      fontSize: "17px",
      lineHeight: 1.7,
      color: "rgba(255,255,255,0.85)",
    }}>
      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>1. The Incantation</h2>

      <p style={{ margin: "0 0 20px" }}>1969--1971</p>

      <p style={{ margin: "0 0 20px" }}>There is a moment halfway through the film adaptation of Fear and Loathing in Las Vegas that I keep replaying in my mind. Raoul Duke is crawling on his back like a Kafkaesque insect on the coarse hotel carpet of the trashed suite at the Mint Hotel, while Nixon’s face blooms across the television screen. The President’s lips move through the ritual of address, but as countless chemicals muddle Duke’s perception, the boundaries of the broadcast begin to ripple. The word “sacrifice” floats free from its syntax and starts to loop, filling the room with its resounding echo. Nixon’s face emerges from the glass and haunts the air above Duke, the word vibrating between incantation and accusation, a prescription recited until it overwrites thought.</p>

      <p style={{ margin: "0 0 20px" }}>Thompson’s genius in this scene was not the cliché of the drug-addled vision but the capacity to recognize, in distortion, the truth of the apparatus itself. This is 1971, but he’s showing us what began November 3, 1969, when Nixon addressed the nation about Vietnam: “And so tonight, to you, the great silent majority of my fellow Americans, I ask for your support.” The line would rewire the nation’s political consciousness, transforming the weariness of the white middle class into a sanctified form of refusal. Nixon’s speech was not for those in the streets, but for Americans exhausted by protest, hungry for official permission to disengage. He didn’t invoke sacrifice as a call for collective action, but as evidence that legitimacy had already been earned: “No one can say that we are not making a sacrifice for peace.” Throughout the speech, sacrifice is the refrain: a bridge between private suffering and public power. In this reframing, disengagement is no longer cowardice or apathy; it is transformed into a national service, a moral accomplishment.</p>

      <p style={{ margin: "0 0 20px" }}>Nixon’s rhetorical machinery operated in a closed circuit, each line crafted to reinforce the others, every appeal designed to dissolve the boundaries between passivity and virtue. “Let us understand: North Vietnam cannot defeat or humiliate the United States. Only Americans can do that.” The adversary is no longer external, but internal; dissent becomes self-destruction, protest a form of sabotage. The act of opposition is recast as a kind of treason, the silent audience as guardians against collapse.</p>

      <p style={{ margin: "0 0 20px" }}>Sacrifice, in Nixon’s lexicon, was always a demand made of someone else. The phrase appeared repeatedly in his speeches, but always attached to invisible exemptions. The President called for unity in the name of peace, which was made to mean the continued prosecution of war. Unity, as he defined it, consisted in the refusal to protest, the agreement to leave hard choices unspoken and unchallenged. The silent majority learned that the highest form of support was to oppose the protestors, to enact citizenship by staying home and letting the machinery run without interference. The spell was efficient because it promised that true sacrifice could be accomplished by insisting that others do the sacrificing. Inaction became a kind of public virtue, a transformation so total that the ordinary rhythms of suburban life were suddenly recast as patriotic rites.</p>

      <p style={{ margin: "0 0 20px" }}>Thompson’s vision, rendered in the hallucinatory grammar of the film, lays bare a pathology that metastasized across five decades. What he saw was not the mere manipulation of language, but the installation of a ritual that would shape every future invocation of sacrifice in American public life. The word would continue to circulate through speeches, op-eds, campaign ads, and newscasts, always carrying the residue of that first spell. It became the engine of selective burden, the instrument by which exemption could be recoded as a moral accomplishment.</p>

      <p style={{ margin: "0 0 20px" }}>The spell demands renewal. Every subsequent administration will find its own version of the ritual, its own way of redeploying the incantation in the service of selective burden and cyclical relief. The logic will persist: exemption becomes virtue, virtue becomes the currency of power, sacrifice is redefined as the obligation of someone else. What Thompson saw through the haze of chemicals was not simply a hallucination, but a diagnosis. The incantation he witnessed in 1971 is still the organizing principle of American public life, repeated endlessly, always promising that the highest form of participation is the power to insist that someone else take your place at the altar.</p>

      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>2. The Architecture of Abdication</h2>

      <p style={{ margin: "0 0 20px" }}>1969 to the late 1970s</p>

      <p style={{ margin: "0 0 20px" }}>Nixon’s 1969 address functioned not only as a speech, but as an intricate choreography of permission and withdrawal. He did not ask the American public to act or even to approve, but rather invited them to retreat into the sanctity of their living rooms and to discover within this retreat a new moral order. The ritual was never named directly, yet its mechanics were unmistakable. Ordinary life, undisturbed by conflict or protest, became a badge of virtue. The broadcast delivered not a call to sacrifice, but a benediction for those who longed to be untroubled by consequence. One could claim innocence and even righteousness by declining to engage, by sustaining the rituals of family and suburb, by maintaining the surface of continuity as history worked itself out elsewhere.</p>

      <p style={{ margin: "0 0 20px" }}>Children, watching this spectacle from the edges of the room, became experts in emotional translation long before they understood the content of politics. They absorbed not only the words, but the way their parents’ bodies relaxed at certain phrases, the way anxiety dissipated when the President spoke of the silent majority and the righteousness of patience. The lesson was not delivered in argument, but in the gentle discipline of the everyday. Safety was achieved not through struggle or negotiation, but by harmonizing with the emotional atmosphere established by adults who had themselves endured wars and depressions and now wished for quiet. These children learned to read the climate of a household, to align themselves with the prevailing mood, to avoid disrupting the equilibrium that promised them a share in the blessings of distance.</p>

      <p style={{ margin: "0 0 20px" }}>The suburbs themselves became a curriculum, teaching the art of exclusion through infrastructure and routine. Streets and schools were planned with deliberation, and their boundaries were justified by a language that was both familiar and elusive. Phrases like “the schools are getting rough” or “the neighborhood is changing” recurred as if they were neutral observations, when in truth they named and defended the new distribution of risk. To say “we’re thinking of the children” was to invoke a moral imperative that required no specifics, only a shared sense that some forms of contact were best avoided. This grammar of abdication, composed of euphemism and code, taught children that virtue could be performed by not naming what everyone already knew. It was possible to master the rules of belonging without ever hearing them spoken aloud.</p>

      <p style={{ margin: "0 0 20px" }}>Throughout the 1970s, these private rituals accumulated into public facts. The great migrations from cities like Detroit, Newark, and St. Louis to their surrounding suburbs were explained in the language of opportunity and prudence, never as an admission of flight or exclusion. The loss of population and shifting tax bases were made invisible by the appearance of new schools and thriving subdivisions. The surface of American life was remade by individual choices that each appeared reasonable, but that together reorganized access, security, and expectation along lines drawn by unspoken agreement.</p>

      <p style={{ margin: "0 0 20px" }}>Children lived inside these changes as if they were natural phenomena. They heard their parents offer reasons for moving or for choosing a different school, reasons always left vague enough to avoid discomfort, but clear enough to signal what could not be admitted. Better meant whiter. Safer meant separated. Opportunity for one group meant the slow, silent erosion of another’s prospects. The arithmetic of scarcity was hidden behind a rhetoric of striving, and the discipline of not noticing became a central part of growing up. Abdication was taught not as an argument, but as a way of managing discomfort, a technique for sustaining the sense of innocence and the illusion of inevitability.</p>

      <p style={{ margin: "0 0 20px" }}>This was not a matter of conspiracy, nor was it achieved through explicit collusion. The real power of abdication was its capacity to present itself as simple consensus, the result of countless decisions made by people who believed themselves moderate, practical, and fair. The public invocation of community values and shared purpose stood in stark contrast to the precision with which boundaries were drawn and maintained. For children who learned to watch and listen, the gap between public language and private certainty became the defining structure of their world.</p>

      <p style={{ margin: "0 0 20px" }}>Cynicism took hold not as a fashionable pose, but as a logical adaptation to a world where the highest adult virtue was practiced indifference. Commitment came to seem naive. Irony and detachment became forms of armor. The system taught that to care too much was dangerous and that presence was costly. The performance of agreement and the avoidance of conflict became prerequisites for belonging, and authenticity became a liability rather than a mark of character.</p>

      <p style={{ margin: "0 0 20px" }}>When these patterns became the inheritance of a new generation, the process adapted to changing circumstances but never lost its essential logic. The language shifted to fit the times. School choice replaced neighborhood schools, merit replaced local control, but the underlying machinery remained. Institutions learned to celebrate inclusion in principle while continuing to protect the status quo in practice. The skill of honoring difference without disturbing the allocation of power or resources became a mark of sophistication. Children who had learned to read the room became adults who learned to read institutions, refining their understanding of what could be altered and what must remain unquestioned.</p>

      <p style={{ margin: "0 0 20px" }}>The architecture of abdication is more than a collection of policies or a map of demographic changes. It is an education in selective attention and an ongoing pedagogy of silence. What is truly handed down from one generation to the next is not a set of opinions or positions, but a disciplined sense of what cannot be seen, what must not be asked, and what will never be said. The work of sustaining comfort by avoiding responsibility continues not through grand declarations, but through the small, daily negotiations of attention and memory. This is not simply unfinished business, but the persistent mechanism by which innocence is inherited and the difficult work of reckoning is indefinitely deferred.</p>

      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>3. The Inheritors</h2>

      <p style={{ margin: "0 0 20px" }}>Late 1970s to 1980</p>

      <p style={{ margin: "0 0 20px" }}>California, 1978. Howard Jarvis barnstorms the state with a gospel beguilingly simple: property taxes are suffocating families, uprooting elders, extracting unearned tribute from households who only want continuity. The message lands with surgical precision. Who would dare to defend a government assessor against a grandmother whose house is slipping from her grasp?</p>

      <p style={{ margin: "0 0 20px" }}>This is the public theater. Beneath it, the machinery of advantage is recalibrating itself for a new era. Proposition 13 will freeze property tax increases at two percent annually, fixed to the date of purchase. Two homes on a single block, identical except for timing of sale, will now exist in parallel universes of obligation. The law applies, in principle, to everyone. In practice, it is an engine of compound inequality. Corporate properties gain the same privilege, but with careful legal maneuvering, corporations can evade reassessment for generations. Chevron and a local grandmother now inhabit the same protected class, though only one employs an army of tax attorneys.</p>

      <p style={{ margin: "0 0 20px" }}>For the generation arriving into their prime years of household formation, the lesson is immediately legible. The Boomers recognize in Prop 13 not just relief from taxes, but an invitation to write the terms of inheritance. Timing supplants effort. The crucial act is not building, but arriving first. They understand that advantage can be crystallized and preserved in the architecture of law. This is not tax reform; it is the creation of a new American aristocracy, one grounded not in lineage but in the date stamped on a closing contract.</p>

      <p style={{ margin: "0 0 20px" }}>The brilliance of the arrangement lies in how quickly its origins are effaced. What begins as populist outcry hardens, almost overnight, into orthodoxy. Proposition 13 becomes constitutional relic, beyond the reach of ordinary politics. The generation that once took to the streets against authority now finds securing privilege far more durable than momentary revolt. Their motives are reframed as civic duty. They are not hoarding, but “protecting property values.” They are not closing doors, but “maintaining neighborhood character.” Every act of self-interest is washed in the language of virtue.</p>

      <p style={{ margin: "0 0 20px" }}>By 1990, the system’s distortions are undeniable. Commercial properties unsold since 1978 are assessed as if explosive appreciation never occurred. The burden shifts toward those least equipped: new buyers, renters, anyone whose stake arrives too late. School districts dependent on property taxes experience hollowing. The once world-class public education system enters slow descent, dragging libraries, parks, and municipal services with it.</p>

      <p style={{ margin: "0 0 20px" }}>Inside the houses secured by constitutional amendment, the world appears stable, even improved. Boomers settle into their roles as stewards of private comfort, increasingly detached from the slow death of public goods. The rhetoric of reform fades, replaced by stories of hard work and prudence. For children growing up in these neighborhoods, the education is visceral. They see it in gradual decay of school buildings, in shuttered library hours, in the broken promise of the swimming pool that no longer opens. These children learn that the world divides between insiders and those who came too late. The public is disappointment. The private is the only security.</p>

      <p style={{ margin: "0 0 20px" }}>This model propagates across the country, acquiring new names but repeating the essential script. Massachusetts enacts Proposition 2½. Michigan installs the Headlee Amendment. Each preserves the logic of temporal entitlement, each sells intergenerational exclusion as defense of ordinary people. By the Reagan era, this architecture is national, woven into what is now called fiscal responsibility.</p>

      <p style={{ margin: "0 0 20px" }}>Yet what emerges is not only an economic order, but an order of memory. The moment of taking, once justified by crisis, becomes cloaked in forgetfulness. The mechanisms of capture recede from view, replaced by narratives of deservingness and discipline. The Boomer generation tells its story as survival and prudence, not exclusion or luck. This is generational amnesia perfected, ensuring that the costs of comfort can be exported without guilt, that the story of sacrifice always stars someone else.</p>

      <p style={{ margin: "0 0 20px" }}>This is the final genius of Proposition 13. It transforms theft into tradition, exclusion into common sense, and memory into a private archive accessible only to those who wrote themselves in while the doors were still open.</p>

      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>4. The Diagnostic</h2>

      <p style={{ margin: "0 0 20px" }}>1980–1999</p>

      <p style={{ margin: "0 0 20px" }}>Bruce Cannon Gibney’s A Generation of Sociopaths reads less like cultural criticism than clinical observation, a systematic cataloging of behaviors so consistent they transcend individual variation and reveal collective pathology. The book’s genius lies not in its provocative title but in its methodical documentation of how a generation that inherited unprecedented prosperity managed to dismantle the very systems that created it, all while maintaining perfect conviction in their own virtue. Gibney, himself a venture capitalist who watched this generation operate from inside their boardrooms and investment committees, brings the diagnostic precision of someone who’s seen the patient up close, who understands that what looks like greed or shortsightedness from the outside reveals itself as something more troubling from within: a fundamental inability to conceive of obligations that extend beyond the self.</p>

      <p style={{ margin: "0 0 20px" }}>But the pathology Gibney describes had been building since Nixon’s spell first took hold. Reagan didn’t create Boomer sociopathy; he gave it presidential permission, transforming what had been individual impulses into national policy. “Government is not the solution to our problem; government is the problem.” The line works as political rhetoric, but decode what it actually meant to the generation hearing it: the systems that built middle-class prosperity, that created the suburban paradise they inherited, that funded the universities where they discovered themselves, these systems were now impediments to further accumulation. Time to dismantle them. But carefully, quietly, with a movie star’s smile that made destruction feel like morning in America.</p>

      <p style={{ margin: "0 0 20px" }}>The extraction begins in earnest. Unions are gutted while speaking of “right to work.” Safety nets are shredded while invoking “welfare queens,” a racist phantom conjured to justify cruelty as fiscal responsibility. Infrastructure rots while cutting taxes for “job creators,” though the jobs created seem always to be elsewhere, for someone else, at wages that would have embarrassed their parents’ generation. Every policy becomes a mechanism for upward wealth transfer, always sold as common-sense reform, as getting government off the backs of ordinary Americans, though the Americans getting relief all seem to live in the same zip codes.</p>

      <p style={{ margin: "0 0 20px" }}>Gibney documents this with actuarial precision: the defunding of public universities precisely as Boomers aged out of them, the cutting of mental health services once their experimental drug phase ended, the dismantling of job training programs once their careers were established. Each cut timed with remarkable accuracy to when that generation no longer needed the service in question. It’s not mere correlation; it’s a pattern so consistent it suggests an instinctive understanding of collective self-interest so refined it needs no explicit communication.</p>

      <p style={{ margin: "0 0 20px" }}>Then comes Clinton, the first Boomer president, born 1946, the literal first year of the boom, as if history itself wanted to mark the transition with clarity. Here’s where liberals comfort themselves with false distinction, imagining that surely their Boomer was different, that the saxophone and the Oxford education and the “I feel your pain” empathy meant something had changed. But Clinton completes what Reagan started, and he does it with brutal efficiency. He declares “the era of big government is over,” as if government had been some occupying force rather than the mechanism that built the middle class his generation inherited.</p>

      <p style={{ margin: "0 0 20px" }}>Watch him work. Welfare “reform” throws millions into poverty while being sold as “empowerment.” NAFTA ships jobs overseas while promising prosperity for all. Glass-Steagall dies with bipartisan approval, Democrats and Republicans joining hands to unleash the financial sector just in time for Boomers to start gambling with their accumulated housing wealth. The crime bill creates the world’s largest prison system while Clinton plays jazz on Arsenio, the incarceration of millions providing the perfect backdrop for suburban comfort.</p>

      <p style={{ margin: "0 0 20px" }}>This is what Gibney’s thesis illuminates: the sociopathy isn’t partisan. It’s generational. Clinton and Gingrich may have feuded over personal scandals, but they agreed on the fundamentals. Dismantle the regulations. Financialize everything. Let the market sort out who deserves to survive. The Boomers had captured both parties, ensuring that regardless of who won elections, their interests would prevail.</p>

      <p style={{ margin: "0 0 20px" }}>By 1999, the machine runs so smoothly you could forget it runs on extraction. The stock market soars to absurd heights, every 401k a lottery ticket. McMansions sprawl across former farmland like metastatic cells, each one identical in its studied uniqueness. Everyone’s house becomes an ATM, home equity lines of credit funding consumption that would have horrified their Depression-era parents. The future has been successfully mortgaged, but the bills haven’t come due yet.</p>

      <p style={{ margin: "0 0 20px" }}>The Millennials were in elementary school when Clinton declared the era of big government over, too young to understand policy but old enough to feel the texture of abandonment. Born into the full flower of Reagan’s America, they experienced the dismantling as natural state; not decay but simply the way things were. Their parents, those forgotten Gen Xers and late Boomers, had already internalized the impossibility of collective solutions. So they invested everything in their children as individual projects, as private solutions to public failures.</p>

      <p style={{ margin: "0 0 20px" }}>This was the participation trophy generation not because they were soft but because their parents understood that actual competition was rigged. Every soccer game where everyone got a medal was a rehearsal for a world where symbolic victories would substitute for material ones. The trophies taught them to perform achievement rather than achieve, to perfect the metrics rather than the substance. They learned to optimize themselves like products because that’s what their parents knew they’d need to become.</p>

      <p style={{ margin: "0 0 20px" }}>By 1999, the oldest Millennials were graduating high school into a world that looked like prosperity but felt like quicksand. The NASDAQ hit 5,000 while college costs had tripled since their parents’ time, but everyone insisted this was the path. They signed the loan papers at eighteen, too young to understand they were volunteering for a new form of sacrifice: mortgaging their futures for the chance to compete in a game already rigged against them. The spell had evolved again. Not “someone else should sacrifice” but “sacrifice your future for entry into a game already rigged against you.”</p>

      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>5. The Bifurcation</h2>

      <p style={{ margin: "0 0 20px" }}>2000–2019</p>

      <p style={{ margin: "0 0 20px" }}>The new millennium brings clarity with the force of revelation: there are now two ways to perform the American spell, and both lead to the same place.</p>

      <p style={{ margin: "0 0 20px" }}>The first erupts after 9/11 like something volcanic and ancient, draped in flags and fury. Bush, born 1946, another first-year Boomer, channels the fear into endless war with the precision of someone who’s been waiting for exactly this opportunity. “You’re either with us or against us.” The silent majority discovers it actually loves being loud, as long as someone else bleeds for the volume. The PATRIOT Act passes with bipartisan enthusiasm, Democrats and Republicans united in their conviction that freedom means letting the government read your email. The wars make brutal sense until they don’t, until it becomes clear that the point isn’t winning but continuing, that the sacrifice of American soldiers and Afghan civilians serves primarily to justify more sacrifice, more contracts, more extraction dressed as liberation.</p>

      <p style={{ margin: "0 0 20px" }}>But here’s where it gets interesting, where the second strain develops in parallel. The professional class, educated and comfortable, develops its own method for maintaining supremacy while feeling good about it. They want their empire with better manners, their wars with exit strategies, their extraction with emotional intelligence. Obama’s election seems like generational change, though barely. The wars continue with drone strikes instead of ground troops, the kill list modernized for the digital age. The surveillance state expands with the kind of efficiency that would have made Hoover weep with envy.</p>

      <p style={{ margin: "0 0 20px" }}>Then comes the financial crisis, and the bailouts reveal everything. Here’s a generation that spent thirty years preaching about moral hazard and personal responsibility, about how welfare creates dependency and how the market must be allowed to work its brutal magic. The same people who cheered when Clinton gutted welfare because single mothers were “gaming the system” for $300 a month suddenly discovered the virtues of government intervention when their portfolios started hemorrhaging. Wells Fargo got $25 billion while foreclosing on families who missed payments by a week. Bank of America swallowed $45 billion in taxpayer money while kicking people out of homes the bank fraudulently claimed to own. The same generation that killed free school lunch programs because “there’s no free lunch” demanded and received the largest free lunch in human history, all to ensure that the generation that gambled the economy into collapse doesn’t have to experience any actual consequences.</p>

      <p style={{ margin: "0 0 20px" }}>Meanwhile, the professional-class Boomers perfect their own version of the con. They speak in the language of progress while defending every structure that maintains their advantage. They live in neighborhoods zoned to exclude anything affordable, send their children to schools funded by property taxes that price out anyone who didn’t buy in 1978, all while maintaining perfect progressive credentials. They post “In This House We Believe” signs on lawns that might as well be moated, vote for Democrats who promise change while ensuring nothing fundamental changes, especially not their property values or their tax advantages or their ability to extract rent from everyone younger and poorer than themselves.</p>

      <p style={{ margin: "0 0 20px" }}>The hypocrisy achieves near-perfect form in places like San Francisco or Brooklyn, where liberal Boomers have created entire economies based on pricing out the very people who make cities function. They’ll march for immigrant rights but vote against the apartment building that might house those immigrants. They’ll post about income inequality from houses that have appreciated 2000% while ensuring through zoning and regulation that no one can build anything that might dilute their investment. They want justice, sure, but not if it affects the neighborhood’s character.</p>

      <p style={{ margin: "0 0 20px" }}>Then comes Trump, born 1946, because of course he fucking was. He doesn’t represent a break from Boomer power but its apotheosis, its final form freed from even the pretense of shame. He makes the con the pitch, says the quiet parts through a megaphone, turns the subtext into text in 280-character bursts. The polite Boomers are horrified, not by the policies but by the presentation. He’s revealing the mechanics of their comfortable compromise, making visible what they’ve spent decades obscuring with bureaucratic language and procedural norms.</p>

      <p style={{ margin: "0 0 20px" }}>But watch closely: both sides run on the same fuel. Whether they’re screaming at rallies or shaking their heads at wine bars, they agree on the fundamental premise that sacrifice is what other people do. The red hats want brown people to pay. The pink hats want someone else to pay, they’re just nicer about it. Both sides will fight to the death to protect their accumulated advantages, their temporal feudalism, their right to extract value from anyone who didn’t get there first.</p>

      <p style={{ margin: "0 0 20px" }}>By 2019, the split is complete but meaningless. Two wings of the same generational project, arguing about tone while agreeing on substance. The loud ones demand sacrifice through cruelty. The quiet ones demand it through systems. Both ensure that someone else always pays the bill, that the generation that inherited the greatest shared prosperity in human history will pass on nothing but debt and degraded systems and a burning planet they’ll be dead before it fully ignites.</p>

      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>6. The Revolution as Lifestyle Brand</h2>

      <p style={{ margin: "0 0 20px" }}>2020–present</p>

      <p style={{ margin: "0 0 20px" }}>The pandemic arrives as a kind of moral stress test for a society long practiced in ritual avoidance. The slogan “We’re all in this together” travels through screens and speakers, spoken by those insulated from danger, to those who confront it daily and without protection. The phrase is emptied of substance with every repetition. Sacrifice is distributed, but only in one direction. Grocery clerks, nurses, drivers, and teachers inherit the risks. The rest inherit the comfort of symbolic solidarity.</p>

      <p style={{ margin: "0 0 20px" }}>Night after night, New Yorkers lean out of windows and clap, striking pans to thank the nurses laboring below. The ritual is public, loud, and costs nothing. Inside the hospitals, protective equipment is rationed. Nurses store single-use masks in paper bags and wear garbage bags for gowns. The applause is not an intervention. It is an anesthetic, transforming real guilt into spectacle and allowing the machinery of abandonment to continue. Later, these same audiences will reject ballot measures for safe staffing or healthcare funding, ensuring that “essential” workers remain essential only as long as they remain replaceable.</p>

      <p style={{ margin: "0 0 20px" }}>The murder of George Floyd creates a rupture, a momentary breach in the containment field. Protests fill the streets, and the urgency is undeniable. Yet almost immediately, the apparatus of performance begins its work. Black Lives Matter becomes a signpost on manicured lawns, a slogan inscribed on windows in neighborhoods where affordable housing is defeated at every vote. Book clubs devour antiracism texts and social media is overtaken by black squares, but municipal budgets remain unchanged and property lines unchallenged. Corporations hire consultants and publish statements, but diversity remains cosmetic. Every act of self-examination is converted into curriculum, reading list, or keynote. Justice becomes the work of self-understanding, while structures remain intact.</p>

      <p style={{ margin: "0 0 20px" }}>When the language of “Defund the Police” explodes into public discourse, it is rapidly metabolized by the logic of administration. Cities hold hearings, launch commissions, and promise oversight, but policing budgets quietly increase and new forms of bureaucratic management absorb the shock. Minneapolis debates abolition, then votes to preserve its department. New York schedules more training. The revolution becomes a calendar of listening sessions and strategic plans. Nothing fundamental moves.</p>

      <p style={{ margin: "0 0 20px" }}>The professionalization of resistance becomes a closed loop. Consultants monetize virtue, delivering workshops to companies that preserve old hierarchies. Universities begin each event with land acknowledgments, admitting to theft while retaining the land and its wealth. Suburbs circulate antiracist bestsellers while maintaining exclusion through price and policy. Performative self-awareness replaces material change. Even critique of the performance is folded back into the cycle, an additional layer of display and reassurance.</p>

      <p style={{ margin: "0 0 20px" }}>Every generation finds its own way to participate. Boomers convert the language of the sixties into new rationalizations for comfort, adopting the vocabulary of inclusion without ceding any advantages secured in earlier decades. Gen X navigates the machinery of compliance with weary intelligence, managing the same institutions they once distrusted, implementing policies they know are insufficient. Millennials inherit the script as therapeutic mandate, learning that progress can be measured by the complexity of their statements and the sincerity of their acknowledgment. Gen Z arrives into a landscape saturated with performance, switching effortlessly from outrage to irony to resignation, understanding that action is always potentially content, always subject to being monetized or surveilled.</p>

      <p style={{ margin: "0 0 20px" }}>The architecture of performance is now total. Every form of engagement risks being metabolized by the machine it claims to oppose. Every call for sacrifice is translated into ritual, every ritual rendered safe by the absence of actual cost. The word “sacrifice” still echoes through public life, demanded constantly, always extracted from those with the least margin, always justified by those whose comfort is secured in advance. The promise of transformation becomes indistinguishable from its simulation. The performance endures, feeding on its own exposure, exhausting the energies that once might have produced change. The revolution has become a mirror, and the image reflected is always someone else’s problem, someone else’s loss, someone else’s duty to endure.</p>

      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>7. The Persistence of the Spell</h2>

      <p style={{ margin: "0 0 20px" }}>1969–2025</p>

      <p style={{ margin: "0 0 20px" }}>Thompson catches something in that hotel room that transcends the particular nightmare of his moment. Nixon’s face pushing through the television screen, the word “sacrifice” detaching from syntax and becoming pure incantation, Duke crawling through the wreckage while the broadcast pursues him through dimensions that shouldn’t exist. This isn’t just about 1971 or Watergate or Vietnam. It’s about what happens when a word gets repeated so long it restructures reality around its repetition, when the broadcast becomes indistinguishable from the air itself.</p>

      <p style={{ margin: "0 0 20px" }}>Fifty-six years later and we’re all breathing it. The word has eaten through everything: through language until it only points outward, through policy until extraction feels inevitable, through possibility until we can’t imagine otherwise. “Sacrifice” doesn’t mean what the dictionary says anymore. It means a kind of mathematical certainty that someone else will pay whatever price needs paying while we perform elaborate rituals to justify our exemption.</p>

      <p style={{ margin: "0 0 20px" }}>Every crisis follows the same pattern now, every disaster unfolds along the same grooves worn deep by repetition. The pandemic proved this with brutal clarity: essential workers died while knowledge workers typed from safety, wealth flowed upward while death flowed down, and we called them heroes instead of paying them. The machine doesn’t need instructions anymore. It knows what to do.</p>

      <p style={{ margin: "0 0 20px" }}>The broadcast runs constantly through every platform, every policy, every possibility we might imagine for living differently. Housing costs that devour entire lives. Medical systems that bankrupt the sick for the crime of sickness. Climate catastrophe distributed precisely along the lines of who can afford to escape and who can’t. We’ve built a civilization on the principle that someone else goes first, bleeds first, breaks first, dies first. Not as conspiracy but as consensus, not as exception but as rule.</p>

      <p style={{ margin: "0 0 20px" }}>The George Floyd protests revealed how deep this runs. Millions in the streets, genuine rage, genuine possibility, and then watch what happens. The revolution becomes another way to feel engaged while risking nothing, another performance in a culture that has perfected performance as a substitute for transformation. We’ll read the books but not change the zoning. We’ll post the black squares but not surrender the advantages. We’ll say the names but not alter the structures that ensure there will always be more names to say.</p>

      <p style={{ margin: "0 0 20px" }}>The most horrifying part isn’t the inequality or the cruelty or the waste. It’s the automation. Nobody needs to enforce this anymore. We enforce it on ourselves, on each other, through ten thousand daily calculations about what’s realistic, what’s possible, what’s worth fighting for. The word “sacrifice” has structured consciousness so completely that we can’t think outside its grammar. Every solution we imagine involves someone else paying the cost. Every future we project assumes the continuation of the present.</p>

      <p style={{ margin: "0 0 20px" }}>Reality has started presenting bills that can’t be forwarded to someone else. The climate doesn’t care about our deferrals. The costs are coming due. And still the broadcast continues, still we tune in, still we wait for someone else to go first, to pay first, to die first if necessary. The spell holds because we hold it. Because we’ve built entire civilizations on the premise that sacrifice is what other people do.</p>

      <p style={{ margin: "0 0 20px" }}>Thompson saw it true: eventually the hallucination becomes the world. Eventually you can’t tell the difference between the drug and reality because they’ve merged, because the distortion has lasted so long it feels like clarity. We live in Nixon’s expanded face now, all of us, and we’ve lived here so long we’ve forgotten it ever had edges, ever had limits, ever had an outside.</p>

      <p style={{ margin: "0 0 20px" }}>Each generation perfected their own dialect of deferral. The Boomers made it policy. Gen X made it irony. Millennials made it a personal brand. Gen Z made it content. Four generations inside the same broadcast, each finding new ways to perform concern while ensuring someone else bleeds first. The machine doesn’t need enforcement anymore; it has something better. It has children raised inside the spell teaching their children that sacrifice is what other people do, that resistance means tweeting harder, that revolution comes with a subscription model.</p>

      <p style={{ margin: "0 0 20px" }}>The horror isn’t that we can’t escape Nixon’s expanded face. It’s that we’ve decorated it, made it home, raised families inside it. We’ve made the hallucination hereditary.</p>

      <p style={{ margin: "0 0 20px" }}>Sacrifice, sacrifice, sacrifice.</p>

      <p style={{ margin: "0 0 20px" }}>Until the word consumes itself. Until there’s no one left to defer to. Until the machine finally grinds to a halt on its own extracted emptiness. But probably not today. Probably not us. Probably someone else first.</p>

      <p style={{ margin: "0 0 20px" }}>Always someone else first.</p>
    </div>
  );
}
