export default function TheGreatGig() {
  return (
    <div style={{
      fontFamily: "var(--body)",
      fontSize: "17px",
      lineHeight: 1.7,
      color: "rgba(255,255,255,0.85)",
    }}>
      <p style={{ margin: "0 0 20px" }}>There are two ways to know The Dark Side of the Moon. One belongs to the people who built it. The other belongs to everyone who arrives inside it. Roger Waters knows the album like an architect knows a cathedral. He knows what each arch carries, which stones are purely structural, which passages are there to move the body where the mind must go. David Gilmour knows it like a master of light knows stained glass. He knows which panes turn sunrise into a sermon, which angle to strike so the room changes temperature. Both kinds of knowledge are complete in their way. Neither allows the thing that keeps happening to strangers. They will never stand in the nave and feel the first shock of the ceiling opening above them.</p>

      <p style={{ margin: "0 0 20px" }}>Waters is the designer of intent here. He drew the map. He wrote the text. He threaded the themes that bind the record to itself. Time, money, conflict, madness, the pressure of ordinary life, the pressure of extraordinary fear. He set the sequence so the questions become a corridor. He chased voices through the Abbey Road hallways and taped them until the truth came out sideways. He turned clocks and registers and helicopters into instruments that argue back. He wanted a record that plays like a diagnosis and he made one. That is authorship of a serious kind, the rare kind where the idea is not just a banner but a structure you can live in while it reorders your sense of living.</p>

      <p style={{ margin: "0 0 20px" }}>Gilmour supplies the color that makes the structure breathe. He sings the lines that have to land with human weight. He bends the notes that have to travel farther than language. His solo on “Time” does not explain mortality, it makes your body understand it. His guitar on “Money” does not condemn greed, it sounds like the pleasure that turns into the trap. His voice carries resignation and defiance in the same breath, which is why the record feels calm even when it is telling you there will not be enough hours.</p>

      <p style={{ margin: "0 0 20px" }}>The others do not merely decorate this house. Richard Wright gives the rooms their air supply. His chords in “Us and Them” open a space that carries more compassion than any lyric could deliver on its own. The piano and organ blend is the record’s conscience, or maybe its memory. “The Great Gig in the Sky” is his progression, a ladder handed to a singer who climbed it beyond words. Clare Torry gave the album a human cry that no language can cage. Nick Mason keeps time that feels like weather rather than math. Alan Parsons checks every seam so the machinery disappears. The people on the interview cards speak the truths that sober people rarely say out loud. The record is a conspiracy of exact choices that add up to inevitability.</p>

      <p style={{ margin: "0 0 20px" }}>Now consider what none of them can have. The first listen. The arrival. The needle drop that is not a studio cue but a summons. The heartbeat that begins not as a loop you have trimmed and filtered but as an omen you were not prepared to meet. The clocks that do not remind you of the day you recorded them but of the day you realized the day is already gone. Waters cannot hear the album’s ideas as questions anymore. They are answers he has already written. Gilmour cannot hear the album’s sounds as miracles anymore. They are decisions he has already taken. Presence is a kind of blindness. To make something is to trade revelation for information.</p>

      <p style={{ margin: "0 0 20px" }}>This is not a criticism of the makers. It is the cost of making. The magician never truly sees the trick. The chef never tastes the first bite in the way a stranger tastes it. The director does not feel the twist that turns an audience to stone. Some part of you can appreciate the effect, perhaps even be proud of it, but the door of surprise has already swung shut behind you. The creation becomes a place you can maintain and defend and even extend, but it is no longer a place you can discover.</p>

      <p style={{ margin: "0 0 20px" }}>Waters seems to understand this and to resent it a little, which is understandable. He spent years expanding the themes that shaped this album into larger dissertations on power and isolation, and sometimes he has tried to reassert authorial control in literal ways. He can rewrite or re record or reorder, and the craft can be impressive, but he still cannot hear the thing like a child who happens to press play on a Tuesday and gets caught by the tide. Gilmour accepts performance as the ritual that remains, and there is real grace in that. He can send the solo into the air for the ten thousandth time and watch the faces change under it, which is a kind of access to wonder even if it is not the same as wonder itself. Both men stand outside the first door, for different reasons and with different temperaments. Both are necessary to the house that keeps welcoming strangers.</p>

      <p style={{ margin: "0 0 20px" }}>What the record understands about time is simple and cruel. The hours you hoard are the hours already gone. The clocks at the start of “Time” are not a gimmick. They are a courtroom. The lyric is a sentence handed down without malice. You have less than you think. The music smiles while it says this, which is why it hurts. “Money” stages a joke that turns out to be a mirror. Everyone laughs at the cash registers, and then the 7/4 rhythm locks into a pleasure that cannot be trusted, and then the solo tells the truth that you felt in your bones long before you had words for it. “Us and Them” offers an argument that refuses to end in victory, which is what adulthood feels like when you are honest. “Brain Damage” keeps the laughter just long enough to set up the admission you did not want to make. “Eclipse” then gathers all of it into a total chord that is less an ending than an inventory. All that you touch, all that you see, all that you taste, all you feel. The record closes with a list because the list is the life. Then the heartbeat returns, which is both mercy and threat.</p>

      <p style={{ margin: "0 0 20px" }}>The miracle is that the album keeps discovering first listeners. A gatefold vinyl spread wide across a shag-carpeted bedroom floor in the seventies, the record itself catching the faint smell of incense and the static crackle of a worn needle. In the eighties, a Maxell cassette with the levels wrong and the hiss unshakable, dubbed from a friend’s older brother who swore this was the only music worth failing algebra for. In the nineties, a compact disc pulled from the wrong jewel case, maybe slipped into your Discman on the school bus, turning an accidental shuffle into revelation. By the two-thousands, a compressed download at three in the morning from Napster or Limewire, filenames mangled, no artwork, no context, just sound flooding cheap Dell speakers like contraband electricity. In the streaming decade, a pair of thin earbuds on a city bus transforms a commute into liturgy; the world outside the window rearranges itself around the soundscape. And in the present, whatever fractured medium delivers it (TikTok fragments, algorithmic playlists, vinyl reissues fetishized by people born after the CD era), the sensation remains intact. The architecture still holds. The medium mutates, but the moment of encounter does not: the sudden recognition that this isn’t just an album but a map of consciousness you didn’t know you needed until it unfolded in your ears.</p>

      <p style={{ margin: "0 0 20px" }}>Here is the irony that makes the work immortal and also a little cruel. Waters set a trap for complacency and cannot be caught by it. Gilmour built a ladder to wonder and cannot climb it. Wright and Mason and Parsons and Torry gave you the tools to reframe your life and cannot pick them up as if they were new. The congregation experiences the sermon as weather. The clergy experience the same event as logistics. Everyone stands in the same room and hears different truths, and both experiences are real.</p>

      <p style={{ margin: "0 0 20px" }}>If you widen the frame you see the same paradox across art. The first time you see the world bend in a certain science fiction movie is an event that cannot be repeated, not even by the people who created it. The finale of a certain television epic closes a door that the writers can never walk through as viewers. This is not a failure. It is the proof that the thing works. A true first time is a one way gate. The work that becomes culture is the work that keeps generating that gate for people who had not yet been born when the blueprint was drawn.</p>

      <p style={{ margin: "0 0 20px" }}>So let the credits be clear. Waters drew the plan and programmed the lights. Gilmour carried the voice that made the plan feel like fate and turned light into weather. Wright filled the air and wrote the chords that taught the record how to care. Mason kept the pulse that allowed the arguments to move. The people on the tapes spoke like human beings who had not yet learned to be careful. Together they raised a structure that keeps granting arrivals to people who do not know what is about to happen to them.</p>

      <p style={{ margin: "0 0 20px" }}>The last truth is the gentlest one. To make something this complete is to accept a sacrifice that is almost holy. You will never be the person who discovers it. You will never hear the heartbeat as a summons that finds you unprepared. You will never be surprised by the clocks. You will never become aware of your life inside that total chord at the end as if it had been written to trap only you. That privilege belongs to the listeners, and it renews itself each day. Somewhere right now a young person or an older person or someone who never thought this music was for them is pressing play. The room is about to tilt. The same record that feels like biography to its makers will feel like a message smuggled out of the future to its new listener. The miracle repeats. The heartbeat continues.</p>

      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>Tab 2</h2>

      <p style={{ margin: "0 0 20px" }}>There are two ways to know The Dark Side of the Moon. One belongs to the people who built it. The other belongs to everyone who arrives inside it. Roger Waters knows the album like an architect knows a cathedral. He knows what each arch carries, which stones are purely structural, which passages are there to move the body where the mind must go. David Gilmour knows it like a master of light knows stained glass. He knows which panes turn sunrise into a sermon, which angle to strike so the room changes temperature. Both kinds of knowledge are complete in their way. Neither allows the thing that keeps happening to strangers. They will never stand in the nave and feel the first shock of the ceiling opening above them.</p>

      <p style={{ margin: "0 0 20px" }}>Waters is the designer of intent here. He drew the map. He wrote the text. He threaded the themes that bind the record to itself. Time, money, conflict, madness, the pressure of ordinary life, the pressure of extraordinary fear. He set the sequence so the questions become a corridor. He chased voices through the Abbey Road hallways and taped them until the truth came out sideways. He turned clocks and registers and helicopters into instruments that argue back. He wanted a record that plays like a diagnosis and he made one. That is authorship of a serious kind, the rare kind where the idea is not just a banner but a structure you can live in while it reorders your sense of living.</p>

      <p style={{ margin: "0 0 20px" }}>Gilmour supplies the color that makes the structure breathe. He sings the lines that have to land with human weight. He bends the notes that have to travel farther than language. His solo on “Time” does not explain mortality, it makes your body understand it. His guitar on “Money” does not condemn greed, it sounds like the pleasure that turns into the trap. His voice carries resignation and defiance in the same breath, which is why the record feels calm even when it is telling you there will not be enough hours.</p>

      <p style={{ margin: "0 0 20px" }}>The others do not merely decorate this house. Richard Wright gives the rooms their air supply. His chords in “Us and Them” open a space that carries more compassion than any lyric could deliver on its own. The piano and organ blend is the record’s conscience, or maybe its memory. “The Great Gig in the Sky” is his progression, a ladder handed to a singer who climbed it beyond words. Clare Torry gave the album a human cry that no language can cage. Nick Mason keeps time that feels like weather rather than math. Alan Parsons checks every seam so the machinery disappears. The people on the interview cards speak the truths that sober people rarely say out loud. The record is a conspiracy of exact choices that add up to inevitability.</p>

      <p style={{ margin: "0 0 20px" }}>Now consider what none of them can have. The first listen. The arrival. The needle drop that is not a studio cue but a summons. The heartbeat that begins not as a loop you have trimmed and filtered but as an omen you were not prepared to meet. The clocks that do not remind you of the day you recorded them but of the day you realized the day is already gone. Waters cannot hear the album’s ideas as questions anymore. They are answers he has already written. Gilmour cannot hear the album’s sounds as miracles anymore. They are decisions he has already taken. Presence is a kind of blindness. To make something is to trade revelation for information.</p>

      <p style={{ margin: "0 0 20px" }}>This is not a criticism of the makers. It is the cost of making. The magician never truly sees the trick. The chef never tastes the first bite in the way a stranger tastes it. The director does not feel the twist that turns an audience to stone. Some part of you can appreciate the effect, perhaps even be proud of it, but the door of surprise has already swung shut behind you. The creation becomes a place you can maintain and defend and even extend, but it is no longer a place you can discover.</p>

      <p style={{ margin: "0 0 20px" }}>Waters seems to understand this and to resent it a little, which is understandable. He spent years expanding the themes that shaped this album into larger dissertations on power and isolation, and sometimes he has tried to reassert authorial control in literal ways. He can rewrite or re record or reorder, and the craft can be impressive, but he still cannot hear the thing like a child who happens to press play on a Tuesday and gets caught by the tide. Gilmour accepts performance as the ritual that remains, and there is real grace in that. He can send the solo into the air for the ten thousandth time and watch the faces change under it, which is a kind of access to wonder even if it is not the same as wonder itself. Both men stand outside the first door, for different reasons and with different temperaments. Both are necessary to the house that keeps welcoming strangers.</p>

      <p style={{ margin: "0 0 20px" }}>What the record understands about time is simple and cruel. The hours you hoard are the hours already gone. The clocks at the start of “Time” are not a gimmick. They are a courtroom. The lyric is a sentence handed down without malice. You have less than you think. The music smiles while it says this, which is why it hurts. “Money” stages a joke that turns out to be a mirror. Everyone laughs at the cash registers, and then the 7/4 rhythm locks into a pleasure that cannot be trusted, and then the solo tells the truth that you felt in your bones long before you had words for it. “Us and Them” offers an argument that refuses to end in victory, which is what adulthood feels like when you are honest. “Brain Damage” keeps the laughter just long enough to set up the admission you did not want to make. “Eclipse” then gathers all of it into a total chord that is less an ending than an inventory. All that you touch, all that you see, all that you taste, all you feel. The record closes with a list because the list is the life. Then the heartbeat returns, which is both mercy and threat.</p>

      <p style={{ margin: "0 0 20px" }}>The miracle is that the album keeps discovering first listeners. A gatefold vinyl spread wide across a shag-carpeted bedroom floor in the seventies, the record itself catching the faint smell of incense and the static crackle of a worn needle. In the eighties, a Maxell cassette with the levels wrong and the hiss unshakable, dubbed from a friend’s older brother who swore this was the only music worth failing algebra for. In the nineties, a compact disc pulled from the wrong jewel case, maybe slipped into your Discman on the school bus, turning an accidental shuffle into revelation. By the two-thousands, a compressed download at three in the morning from Napster or Limewire, filenames mangled, no artwork, no context, just sound flooding cheap Dell speakers like contraband electricity. In the streaming decade, a pair of thin earbuds on a city bus transforms a commute into liturgy; the world outside the window rearranges itself around the soundscape. And in the present, whatever fractured medium delivers it (TikTok fragments, algorithmic playlists, vinyl reissues fetishized by people born after the CD era), the sensation remains intact. The architecture still holds. The medium mutates, but the moment of encounter does not: the sudden recognition that this isn’t just an album but a map of consciousness you didn’t know you needed until it unfolded in your ears.</p>

      <p style={{ margin: "0 0 20px" }}>Here is the irony that makes the work immortal and also a little cruel. Waters set a trap for complacency and cannot be caught by it. Gilmour built a ladder to wonder and cannot climb it. Wright and Mason and Parsons and Torry gave you the tools to reframe your life and cannot pick them up as if they were new. The congregation experiences the sermon as weather. The clergy experience the same event as logistics. Everyone stands in the same room and hears different truths, and both experiences are real.</p>

      <p style={{ margin: "0 0 20px" }}>If you widen the frame you see the same paradox across art. The first time you see the world bend in a certain science fiction movie is an event that cannot be repeated, not even by the people who created it. The finale of a certain television epic closes a door that the writers can never walk through as viewers. This is not a failure. It is the proof that the thing works. A true first time is a one way gate. The work that becomes culture is the work that keeps generating that gate for people who had not yet been born when the blueprint was drawn.</p>

      <p style={{ margin: "0 0 20px" }}>So let the credits be clear. Waters drew the plan and programmed the lights. Gilmour carried the voice that made the plan feel like fate and turned light into weather. Wright filled the air and wrote the chords that taught the record how to care. Mason kept the pulse that allowed the arguments to move. The people on the tapes spoke like human beings who had not yet learned to be careful. Together they raised a structure that keeps granting arrivals to people who do not know what is about to happen to them.</p>

      <p style={{ margin: "0 0 20px" }}>The last truth is the gentlest one. To make something this complete is to accept a sacrifice that is almost holy. You will never be the person who discovers it. You will never hear the heartbeat as a summons that finds you unprepared. You will never be surprised by the clocks. You will never become aware of your life inside that total chord at the end as if it had been written to trap only you. That privilege belongs to the listeners, and it renews itself each day. Somewhere right now a young person or an older person or someone who never thought this music was for them is pressing play. The room is about to tilt. The same record that feels like biography to its makers will feel like a message smuggled out of the future to its new listener. The miracle repeats. The heartbeat continues.</p>
    </div>
  );
}
