export default function TheLessonsWeBuried() {
  return (
    <div style={{
      fontFamily: "var(--body)",
      fontSize: "17px",
      lineHeight: 1.7,
      color: "rgba(255,255,255,0.85)",
    }}>
      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>Bronx, New York. October 30, 2001.</h2>

      <p style={{ margin: "0 0 20px" }}>Game 3 of the World Series, Yankees against the Diamondbacks, and George W. Bush was about to step into history. Not with policy, not with words, but with a baseball.</p>

      <p style={{ margin: "0 0 20px" }}>He emerged from the dugout in a loose FDNY jacket that hung awkwardly from his shoulders. The jacket transformed him instantly from politician to avatar of the city's pain. It belonged to someone else, someone who had run into burning buildings while others ran out. Now it draped the president like borrowed grief, making him both smaller and larger than himself. Underneath was a Kevlar vest, thick and obvious enough to shape the way his body moved, a reminder that even here, even in this cathedral of American normalcy, danger lurked. This was no ordinary ceremonial pitch. The crowd rose as one, Yankee Stadium convulsing with noise that was neither quite celebration nor mourning but something new, something that had no name yet. Bush walked slowly toward the mound, each step measured, conscious of its weight.</p>

      <p style={{ margin: "0 0 20px" }}>The moment belonged to Bob Sheppard, the Yankees' legendary public address announcer. His voice had introduced players for half a century, a slow, deliberate cadence that made even journeymen sound immortal. Tonight his baritone became something else entirely. It became an invocation, a summoning. "Ladies and gentlemen, the President of the United States." Each word descended into the stadium like scripture, heavy with meaning that went beyond baseball, beyond even this moment. The air itself seemed to thicken with ceremony. Bush didn't flinch. He strode past the safety of the grass and onto the rubber itself, sixty feet six inches away from home plate. That choice mattered. Presidents typically threw from closer, from safer ground. To throw from the mound was to prove authenticity, to risk humiliation in front of a grieving nation. The cameras zoomed in, waiting for failure or redemption.</p>

      <p style={{ margin: "0 0 20px" }}>He threw. A strike. Clean, perfect, cutting through the October air with startling precision. Yankee Stadium exploded. Not for the game, which had become suddenly irrelevant. This wasn't about baseball anymore. This was theater, but theater of the most essential kind, the kind that creates reality rather than reflecting it. Sheppard sealed the ritual with a calm benediction: "Thank you, Mr. President." Bush stood flanked by Yankees manager Joe Torre and Diamondbacks skipper Bob Brenly, a tableau of perfect symmetry, and then the chant began: "USA! USA! USA!" The sound was volcanic, rolling through the stadium with a force that left no space for ambivalence, no room for questions. Bush raised his thumb, proud and dignified, and the roar only grew louder, feeding on itself, becoming something beyond human voices.</p>

      <p style={{ margin: "0 0 20px" }}>That pitch has been replayed for two decades as proof of resilience, as the moment when baseball helped heal the nation. But strip away the swelling strings of the highlight reels, remove the soft focus of memory, and what you see is stranger and more troubling. A grieving country needed a baseball diamond to stage its faith that strength could be performed into existence. The ballpark became a cathedral. The president was priest. The pitch was sacrament. And the chant was liturgy, a commandment disguised as pride. That night was when mourning became ritual, when grief hardened into something useful for power. That night was when "Never Forget" stopped being a plea and became an order, when memory transformed from private sorrow into public duty.</p>

      <p style={{ margin: "0 0 20px" }}>But to understand why that mattered, why that transformation would reshape not just our grief but our nation, you have to rewind seven weeks.</p>

      <h2 style={{ fontFamily: "var(--serif)", fontSize: "24px", fontWeight: 500, color: "#d4822a", margin: "40px 0 16px", lineHeight: 1.3 }}>Sarasota, Florida. September 11, 2001.</h2>

      <p style={{ margin: "0 0 20px" }}>The president sat in a second-grade classroom at Emma E. Booker Elementary School, a grown man perched absurdly on a child's chair, holding a copy of The Pet Goat. He smiled stiffly as the children stumbled through their reading, their voices high and uncertain. The scene was crafted for cameras: the president as educator, as father figure, as man of the people. Then Andrew Card leaned down and whispered sixteen words that would divide history: "A second plane hit the second tower. America is under attack." The footage is infamous, scrutinized frame by frame like the Zapruder film. Bush's eyes flick once, twice, then fix forward on nothing. His jaw clenches. For seven long minutes he does nothing. He sits. He stares. He holds the book like a life raft.</p>

      <p style={{ margin: "0 0 20px" }}>Those minutes have been dissected endlessly, usually with derision. Why didn't he act? Why didn't he leave? Why sit frozen in front of children while the country burned? But there is another truth here, one harder to admit because it humanizes a figure we need to be larger than human. Bush had not signed up for this. He had run for president to restore his family name, to finish his father's unfinished business, to prove that the son could succeed where the father had stumbled. He had campaigned on tax cuts, on education reform, on the kind of steady, forgettable governance that made presidents ceremonial rather than catastrophic. His vision of the presidency was managerial, not mythological. Catastrophe came anyway, and it caught him in a Florida classroom with a children's book in his hands, dressed for a photo op rather than history.</p>

      <p style={{ margin: "0 0 20px" }}>In that chair he wasn't commander-in-chief. He was a man ambushed by history, a son dwarfed by sudden legacy, a politician thrust into a role that no amount of breeding or training had prepared him for. The sympathy here is important, not because it excuses what came after, but because it reveals something essential about both leadership and the country. We were unprepared, and in that moment, we all knew it. America, like its president, had believed itself immune to history, protected by oceans and prosperity from the kinds of ruptures that shaped other nations. The planes revealed this as fantasy. We were as vulnerable as anyone, as small as anyone, as human as anyone.</p>

      <p style={{ margin: "0 0 20px" }}>But that image of vulnerability has been systematically buried. You won't see those seven minutes replayed with triumphant strings. You won't see them on stadium jumbotrons during patriotic ceremonies. Instead, we sanctify the strike at Yankee Stadium. Bush's trajectory was carefully rewritten, edited like film. The seven minutes of paralysis were erased from the national memory, replaced by that perfect pitch. The clean throw became his defining image, the one that turned him from an unready son into the avatar of American resolve, the poster child of Never Forget.</p>

      <p style={{ margin: "0 0 20px" }}>And as Bush transformed, so did the country. Nations, like individuals, choose their self-portraits in moments of crisis. We could have chosen the vulnerable truth of Sarasota, acknowledged our unreadiness, our confusion, our essential humanity. Instead, we chose the performance at Yankee Stadium. We mirrored our president's transformation. We buried our hesitation, our confusion, our smallness, and replaced them with theater. We chose the strike over the silence, the chant over the hesitation. We accepted ritual in place of reckoning. We began editing our own reel, cutting out everything that didn't fit the story we needed to tell ourselves.</p>

      <p style={{ margin: "0 0 20px" }}>What came next was uglier than the images replayed every September, uglier because it revealed what "Never Forget" would actually mean in practice. Hate crimes exploded in the weeks after the attacks. Four days later, in Mesa, Arizona, a man named Frank Roque shot and killed Balbir Singh Sodhi, a Sikh gas station owner who had been planting flowers outside his business, tending to beauty in a world suddenly ugly. Roque claimed he was avenging the attacks. He shouted, "I stand for America all the way," as police arrested him. Sodhi wore a turban, and that was enough to mark him as the enemy in the new America, where grief had already curdled into rage that needed targets, any targets. The murder barely registered in the national story. There were dozens like it. Mosques vandalized, families harassed, children beaten at school, women having their hijabs ripped off in grocery stores. Never Forget had already begun to mean never forgive anyone who looks like the invented enemy.</p>

      <p style={{ margin: "0 0 20px" }}>By the spring of 2002, the candlelight vigils were gone. What remained were bumper stickers. “These Colors Don’t Run,” “United We Stand,” decals slapped onto pickup trucks and storefronts, printed cheap and fast, sold in gas stations next to energy drinks and beef jerky. For a few months they looked sharp, bold, defiant. Then the weather set in. Rain smeared the red into pink, the blue into something closer to gray. The adhesive loosened. The corners curled. The slogans began to melt down the sides of fenders, ghostly streaks of dye trailing like blood in water. These colors did run. They ran everywhere.</p>

      <p style={{ margin: "0 0 20px" }}>And somehow that image of the stickers bleeding themselves into illegibility captures more truth than the solemn ceremonies ever could. Memory sold retail, applied quick, degraded fast. Grief mass-produced until it became residue. Patriotism not as permanence but as runoff.</p>

      <p style={{ margin: "0 0 20px" }}>At the same time, the state built a surveillance machine that still watches us today. Airports turned into theaters of suspicion and submission. Shoes off, belts off, laptops out, liquids surrendered, tiny shampoo bottles bagged like contraband. A choreography of humiliation that had little to do with actual security but everything to do with performing compliance. The Patriot Act authorized sweeping surveillance powers, and what was sold as emergency law became the permanent architecture of American life. We were told it was temporary, necessary, a small price for safety. It was none of these things. The dragnet expanded until it swallowed daily life. Phone calls monitored, emails scanned, bank accounts flagged, internet histories archived. The state no longer needed probable cause to watch its citizens; suspicion became universal and permanent. We now carry tracking devices voluntarily in our pockets, having internalized surveillance so completely that we pay for the privilege.</p>

      <p style={{ margin: "0 0 20px" }}>We normalized it all. We lined up barefoot in airports, holding our pants up with one hand and our passports with the other, pretending this ritual made us safer. We joked about it. We accepted it. The absurdity became routine, and the routine became invisible. This was the true genius of Never Forget: it froze us in perpetual performance, trained us to act out our grief and fear every time we traveled, every time we stood for an anthem, every time we repeated the phrase. We became actors in our own tragedy, and the performance became more real than the reality it replaced.</p>

      <p style={{ margin: "0 0 20px" }}>And then came Baghdad. March 2003. “Shock and Awe” broadcast live, the sky above the city lit like a slot machine. Green tracers arced through the night, buildings burst into fire, and anchors narrated it as if it were a fireworks display. This was not the silence of Sarasota or the theater of Yankee Stadium. This was the third act, the moment the performance became empire. The pitch over the plate had bloomed into missiles over a capital, grief fully converted into spectacle, mourning transformed into war. The justifications were hollow: phantoms of weapons of mass destruction, insinuations of connections that never existed. But by then the truth didn’t matter. The rituals had done their work. To question was betrayal. To dissent was to dishonor the dead. The chants of “USA” that echoed through Yankee Stadium were now implicit in every bombing run, every invasion, every justification. Never Forget had completed its transformation: not grief, not memory, but obedience.</p>

      <p style={{ margin: "0 0 20px" }}>So we invaded. We killed exponentially more civilians abroad than were lost in New York, Washington, or Pennsylvania. We destabilized entire regions, created power vacuums that would birth new horrors. We built secret prisons, tortured people in ways that would have seemed inconceivable on September 10th, told ourselves that brutality was defense, that becoming monstrous was the price of fighting monsters. Never Forget had become never question, never hesitate, never stop.</p>

      <p style={{ margin: "0 0 20px" }}>This is the deepest irony: the attacks themselves did not destroy America. They were never meant to. Nineteen men with box cutters could not bring down a superpower. They were meant to provoke us into destroying ourselves, to trigger an autoimmune response where our own defenses would attack the body they were meant to protect. And that is precisely what we did. We made war on the world and on ourselves. We shredded liberties in the name of liberty, normalized surveillance in the name of freedom, militarized our police, poisoned our politics, taught ourselves to fear our neighbors.</p>

      <p style={{ margin: "0 0 20px" }}>The towers fell once. Our responses have kept falling ever since.</p>

      <p style={{ margin: "0 0 20px" }}>Every year the footage plays again. The towers fall in endless loops on television and computer screens. The smoke billows, the dust clouds roll, bodies fall from windows in images too terrible to show but too important to forget. Politicians speak solemnly at podiums. Ceremonies are held at memorial sites. The phrase is repeated like an incantation: "Never Forget." But what we preserve are the images, not the lessons. We remember the spectacle, not the aftermath. We keep the wound vivid and fresh so that we never have to examine the infection that spread from it.</p>

      <p style={{ margin: "0 0 20px" }}>The real lessons lie buried beneath the ritual. They tell us that grief can be manipulated with terrifying ease, transformed from private sorrow into public weapon. They tell us that patriotism can be weaponized into blind obedience, that flags can become blindfolds. They tell us that America is not immune to history but uniquely vulnerable to fear precisely because we believed ourselves uniquely immune to history. They tell us that democracies can transform themselves into something else while still calling themselves democracies, that freedom can be dismantled in freedom's name.</p>

      <p style={{ margin: "0 0 20px" }}>These are lessons that could have changed us, could have taught us humility, could have forced us to question our myths about ourselves. They could have helped us understand that strength sometimes looks like admitting weakness, that true security comes from justice rather than surveillance, that healing requires honesty about the wound. Instead, we buried these lessons. We replaced them with empty rituals: stadium ovations, TSA checkpoints, endless war footage framed as triumph, yellow ribbons on SUVs. We chose the strike at Yankee Stadium over the silence in Sarasota. We chose the edited reel over the raw footage.</p>

      <p style={{ margin: "0 0 20px" }}>Some might argue that the rituals were necessary, that a traumatized nation needed the theater before it could handle the truth, that performance was a kind of survival. Perhaps there's truth in this. Perhaps we needed to act strong before we could actually be strong. But twenty-four years later, we're still performing. The emergency has become permanent. The exception has become the rule. The theater has become reality.</p>

      <p style={{ margin: "0 0 20px" }}>Twenty four years later, we are still living inside that choice. The wound is not the towers themselves. It is the way we edited the reel, the way we chose to sanctify strength and erase hesitation, the way we turned mourning into obedience and obedience into policy. “Never Forget” has never been about memory. It has always been about burial.</p>

      <p style={{ margin: "0 0 20px" }}>And every September, when the ceremonies return and the footage plays again, we pick up the shovels ourselves. Not reluctantly, not under duress. We do it gratefully. The ritual comforts us. The lies soothe us. We bury the lessons because remembering them would mean remembering who we became. A nation that shouted louder instead of thinking harder. A people who wanted the roar of a stadium more than the silence of reflection. Citizens who traded freedom for theater and called it strength.</p>

      <p style={{ margin: "0 0 20px" }}>We became fearful. Vengeful. Eager to be deceived. We mistook bombs falling on Baghdad for dignity restored. We applauded surveillance as if it were liberty. We congratulated ourselves for unity while ignoring that unity was purchased with blood, often the blood of strangers who never asked to be included in our grief.</p>

      <p style={{ margin: "0 0 20px" }}>That is the real story buried under “Never Forget.” Not the day itself, not the images of fire and collapse, but the aftermath we demanded. The attack worked. Not because it toppled towers, but because it toppled us.</p>
    </div>
  );
}
