export default function YourHandsHaveNothingToDo() {
  return (
    <div style={{
      fontFamily: "var(--body)",
      fontSize: "18px",
      lineHeight: 1.7,
      color: "rgba(255,255,255,0.85)",
    }}>
      <p style={{ margin: "0 0 20px" }}>There is a ritual happening in the feed. Someone posts a video of federal agents dragging a man into an unmarked van. Below it, the comments: I can't believe this is happening. How is this happening? This is not normal.</p>

      <p style={{ margin: "0 0 20px" }}>It has been a decade. It is, by now, extremely normal.</p>

      <p style={{ margin: "0 0 20px" }}>The shock is the tell. Not because the feeling is not real, but because the feeling has become the point. The bumfuzzlement, the performed confusion, the insistence on being appalled as though appalled were a position. How can this be happening? The question stopped being genuine years ago. Now it is a posture. A way of saying: I am still one of the good ones. I still notice. I am still here, not yet numb, not yet complicit, still registering the horror with appropriate horror. The performance of confusion has become its own credential, a badge that says: I have not yet surrendered my capacity for outrage. But the outrage circles. It feeds on itself. It goes nowhere. The confusion is not a step toward understanding; it is a destination. And that destination is comfortable, because confusion absolves. If I am still shocked, I cannot be implicated. If I am still asking how, I do not have to answer what now.</p>

      <p style={{ margin: "0 0 20px" }}>This mindset is related to, but sits on the other side of the political spectrum from, the "thoughts and prayers" community that materializes after every mass tragedy. Both behaviors, the keyboard activism and the thoughts-and-prayers gang, present an external display of action while remaining thoroughly parked. It is truly the thought that counts for these people, many of whom are unwilling to spare a thought for anything outside their pre-existing positions. But the virtue-hungry liberals do something beyond the thoughts-and-prayers crowd's perfectly corrupted version of wu wei: they admonish those who do not play along. Why did you not change your profile picture? Why are you not posting about ICE? Why are you acting like none of this is happening?</p>

      <p style={{ margin: "0 0 20px" }}>It is the last question that sends me somewhere I cannot easily return from. The logic, as far as I can understand it, is that unless you are actively engaged in the Manichaean struggle of the algorithmic feed, you are not sufficiently co-enduring the pain of those being abducted, killed, orphaned, et cetera. You are guilty of the sin of not displaying your proxy suffering with sufficient visibility. The demand is not that you act, but that you perform. And the performance must be public, legible, continuous. Silence is interpreted not as focus or strategy or the conservation of energy for actual intervention, but as complicity. The feed requires constant testimony. To step away is to betray.</p>

      <p style={{ margin: "0 0 20px" }}>I see those same videos of people being killed on the streets. I see the same news stories, redacted, rewritten, optimized to keep the alarm bells ringing in our collective consciousness. And despite declared belief to the contrary, it is possible to feel the same levels of sympathy, empathy, rage, and frustration at the inability to do something meaningful without turning my feed into a recursive loop of tragedy porn.</p>

      <p style={{ margin: "0 0 20px" }}>But here is what I cannot escape: witnessing someone else's suffering does not alleviate their suffering. So what does it do? What happens to the one who watches?</p>

      <p style={{ margin: "0 0 20px" }}>Byung-Chul Han, writing about digital culture in In the Swarm, makes a distinction that proves useful here: between spectare and respectare. Both are Latin, both involve looking. But spectare is the root of spectacle. It is voyeuristic. It stares. Respectare, on the other hand, is where we get "respect." It means to look back, to look again, to consider. Respect requires distance. Spectacle consumes it. The distinction matters because it names two fundamentally different relationships between the viewer and the viewed. One collapses the space between them into consumption; the other maintains the gap that allows for genuine encounter. The feed, by its architecture, selects for spectare. The scroll is hungry. The algorithm rewards engagement, and engagement is a form of consumption. You do not deliberate over what you see. You react. You share. You move on. The respectful gaze, the one that pauses and considers, is structurally discouraged. There is always more. There is always next. The capacity for consideration atrophies under the pressure of endless supply.</p>

      <p style={{ margin: "0 0 20px" }}>What happens when suffering enters the feed? It becomes spectacle. The distance that would allow for genuine consideration collapses into the infinite scroll. You witness, but witnessing has been restructured. It is no longer an encounter with another person's reality. It is content. And content, by its nature, is consumed. The suffering is real, somewhere. But here, on your screen, it has been flattened into the same plane as everything else: ads, memes, updates from people you barely remember, sponsored posts, outrage, entertainment, death. The architecture does not distinguish. It cannot. Distinction is your job, and the architecture is designed to exhaust your capacity for it.</p>

      <p style={{ margin: "0 0 20px" }}>Han argues that digital communication has completed a transformation already underway: the collapse of the citizen into the consumer. Citizens deliberate; consumers select. Citizens are defined by responsibility to a community; consumers are defined by preference. "Shopping presupposes no discourse," Han writes. "Consumers buy what they wish, following personal inclination. Like is their motto." The suffering of strangers arrives in the same feed as ads for Alo yoga pants, bespoke men's subscriptions, and memes about generational trauma. Everything is consumed or discarded according to the same logic. You do not deliberate over whether to engage with an atrocity. You like it or you scroll past. The verb itself has been colonized. To like now means to acknowledge, to register, to signal that you have seen. It does not mean to approve. But the slippage is instructive. The platform has no category for grief that does not also function as engagement. Your sorrow feeds the machine the same way your joy does. Both are data. Both are fuel.</p>

      <p style={{ margin: "0 0 20px" }}>But there is something darker than consumption at work here, something Han identifies in the transformation of the subject into the project. We understand ourselves as self-designing, self-optimizing. The self is something to be built, curated, displayed. And in this framework, the suffering of others becomes raw material. Not for solidarity. For self-construction. The atrocity you share is not only a statement about the world; it is a statement about you. It says: I am the kind of person who sees this, who cares about this, who is moved by this. The other person's pain becomes a brick in the edifice of your public self. This is not necessarily cynical. You may genuinely care. But the structure does not distinguish between genuine care and its performance. And over time, the performance becomes easier to produce than the feeling, and the feeling atrophies from disuse, and what remains is the gesture without the substance, the share without the solidarity.</p>

      <p style={{ margin: "0 0 20px" }}>The feed does not connect you to others; it reflects you back to yourself. Han describes the narcissistically depressive subject as one who hears only echoes of itself, for whom meaning exists only when it manages to recognize itself again, for whom the world appears only in adumbrations of the self. You do not see the suffering. You see yourself seeing the suffering. You see yourself as the kind of person who witnesses, who cares, who posts. The other vanishes. What remains is your own moral reflection, optimized for display. This is the final destination of the like: not engagement with the world, but confirmation of the self. The feed becomes a mirror, and you scroll through it looking for your own face, and sometimes you find it in the suffering of strangers, and you feel something that might be compassion or might be recognition, and you cannot tell the difference anymore, and perhaps it no longer matters.</p>

      <p style={{ margin: "0 0 20px" }}>[I am writing this at 10:47 p.m. on a Wednesday. The same feed I am describing is open on another device. I have not closed it. I am not going to close it. The distance I am performing right now, the critical remove, is happening 18 inches from the thing it is critiquing. I am not outside the mirror. I am in it, writing about the mirror, watching myself write about the mirror, wondering if the writing is another form of the looking or an escape from it or both.]</p>

      <p style={{ margin: "0 0 20px" }}>Of course, Han might be overstating the case. Not every act of digital witness is narcissism dressed in mourning clothes. Some people are genuinely trying to find a way through, to make the unbearable visible, to refuse the comfortable silence that power prefers. The problem is that the medium does not care about intention. The feed flattens everything. Your grief and your performance of grief become indistinguishable, not because you are a fraud, but because the structure does not permit the distinction. You can mean it completely and still be trapped in the logic of spectacle. The algorithm does not know the difference between a cry for justice and a bid for engagement. It only knows what gets shared. And so the sincere and the cynical are processed identically, rendered equivalent, fed into the same machine that converts all human expression into metrics.</p>

      <p style={{ margin: "0 0 20px" }}>If Han diagnoses the self as project, Susan Sontag asks what the looking does to the body that looks. In Regarding the Pain of Others, she identifies an asymmetry that has only intensified since she wrote it: the image extends our capacity to see while leaving our capacity to act unchanged. The distance collapses in only one direction. You witness a murder in Minneapolis from your living room in nearly real time. Your nervous system responds. The eye is connected to the brain, the brain to the nervous system, and the cascade fires through every past memory and present feeling. But your hands have nothing to do. You are flooded with emergencies you cannot touch.</p>

      <p style={{ margin: "0 0 20px" }}>Sontag is skeptical of the easy diagnosis of compassion fatigue, the claim that we have simply seen too much. The problem is not numbness. It is frustration. Compassion is unstable; it needs to be translated into action, or it withers. The feeling is real. The arousal is real. But there is nowhere for it to go. The frustration mounts. You care, and your caring changes nothing, and the gap between the feeling and its effect becomes unbearable, and eventually you either find something to do or you find a way to stop feeling. Most people oscillate between these poles: brief spasms of action followed by retreats into numbness or distraction. The system counts on this oscillation. It prefers it to sustained engagement. Sustained engagement is dangerous. Oscillation is manageable.</p>

      <p style={{ margin: "0 0 20px" }}>The frustration of impotence does not disappear. It metabolizes. We turn the guilt outward, toward the photographer, the platform, the algorithm, because we cannot turn it into action. The discourse about the ethics of looking is often a displacement of the frustration of not being able to act. We debate whether it is appropriate to share the video, whether the platform should allow it, whether the photographer was exploitative, because these debates are actionable. We can have opinions about them. We can take positions. We can perform discernment. Meanwhile, the person in the video remains dead, and our discernment changes nothing.</p>

      <p style={{ margin: "0 0 20px" }}>[I re-read that line in my kitchen. Not metaphorically. Literally in my kitchen, no heat in the house, the deaths autoplaying in the next room because I forgot to hit pause before I got up. What surgery have I performed? What wound have I closed? The honest answer is: nothing. I have witnessed, and my witnessing has changed nothing, and I have continued to witness, and the witnessing has become its own activity, its own justification, its own alibi. The essay as receipt. Proof of attendance at the atrocity.]</p>

      <p style={{ margin: "0 0 20px" }}>This is proximity collapse: the signals of nearness without the conditions of nearness. Your body believes you are there. Your hands know you are not. The dissonance is the condition. You feel implicated, involved, responsible, but you are also helpless, distant, spectatorial. Both are true. Neither cancels the other. And the toggling between them, the constant negotiation, is exhausting in a way that is difficult to name and impossible to escape.</p>

      <p style={{ margin: "0 0 20px" }}>Sontag's frustration assumes there is something one could do, if only one could find the right channel, the right action. Mark Fisher's contribution is grimmer: what if there is not? What if the alternatives have been systematically dismantled, rendered not just impractical but unthinkable?</p>

      <p style={{ margin: "0 0 20px" }}>This is the core of Capitalist Realism: "It is easier to imagine the end of the world than it is to imagine the end of capitalism." The system has colonized not just the economy but the imagination. There is no outside. There is no lever. And by lever I mean exactly what the word implies: a mechanism that converts individual force into systemic movement. Archimedes said give me a lever long enough and I will move the world. The point of Fisher's analysis is that such mechanisms have been dismantled, or captured, or were never as real as we believed. The vote. The protest. The boycott. The union. Each has been either broken or reduced to a simulation of itself. What remains are gestures that feel like levers but connect to nothing. You pull, and nothing moves, and you are told the problem is that you did not pull hard enough, or in the right direction, or with the right technique, and you try again, and nothing moves, and eventually you stop believing in levers.</p>

      <p style={{ margin: "0 0 20px" }}>The absence of alternatives produces a specific kind of paralysis Fisher calls reflexive impotence. You know things are bad. More than that, you know you cannot do anything about it. But that knowledge is not a passive observation of an already existing state of affairs. It is a self-fulfilling prophecy. The belief that nothing can be done ensures that nothing is done, which confirms the belief. The loop closes. And the loop is not just individual; it is collective. Everyone knows, and everyone knows that everyone knows, and the shared knowledge becomes a kind of permission structure for inaction. We are all trapped, so none of us is responsible. The trap absolves.</p>

      <p style={{ margin: "0 0 20px" }}>This is where Han, Sontag, and Fisher converge: in the architecture of the trap itself. Han shows how the self becomes raw material for its own curation, how suffering is metabolized into identity. Sontag shows how the body is flooded with emergencies it cannot touch, how compassion without action curdles into frustration. Fisher shows how the very possibility of action has been foreclosed, how the imagination itself has been colonized. Together they describe a closed system. The feed produces the arousal. The arousal has nowhere to go. The frustration turns inward or sideways. The posting becomes the action. The self becomes the project. And nothing changes except the metrics.</p>

      <p style={{ margin: "0 0 20px" }}>What would you do if you were not posting and sharing? Vote for Democrats who enabled this? Call a voicemail? Donate to an NGO that spends 40% on overhead? The liberal infrastructure offers no lever. It offers participation in a system that has already demonstrated its inadequacy. The share button is not chosen over better options. It is chosen because the better options do not exist, or have been systematically dismantled, or require a kind of risk and sacrifice that the comfortable are not willing to make. And so the share button becomes the action, the only action available, and the action accomplishes nothing, and the accomplishing nothing is known in advance, and the knowledge does not stop the action, because the alternative to inadequate action is no action at all, and no action feels worse, even though the outcomes are identical.</p>

      <p style={{ margin: "0 0 20px" }}>[I have pressed the share button. I have pressed it knowing. I have felt the small pulse of satisfaction that comes from having done something, and I have known even in the feeling that the something was nothing, and I have pressed it again the next day. The knowing does not stop the pressing. If anything, the knowing makes it worse, because now I am not even naive. I am complicit and aware and still pressing. The essay you are reading is a longer, slower version of the share button. It will reach more people and accomplish the same amount.]</p>

      <p style={{ margin: "0 0 20px" }}>Fisher links this back to the psychological: the absence of alternatives gets internalized as personal failure. You cannot change the system, so you blame yourself for not doing enough, not caring enough, not posting enough. The structural problem becomes a chemical imbalance, a family history, a diagnosis. The guilt produces more posting. The posting produces more guilt. Fisher calls this the privatization of stress. Depression, endemic and exploding, reframed as personal deficiency rather than what it actually is: the psychic cost of living under conditions that offer no exit. We are told to practice self-care, to manage our anxiety, to find healthy coping mechanisms, as though the problem were our inability to adapt rather than the conditions to which we are being asked to adapt. The system produces the suffering and then sells us the remedy, and the remedy does not address the cause, and we return again and again to the market of solutions, each one promising relief, none of them delivering it, all of them profitable.</p>

      <p style={{ margin: "0 0 20px" }}>But Fisher does not leave it there. We must convert widespread mental health problems from medicalized conditions into effective antagonisms, he writes. Affective disorders are forms of captured discontent; this disaffection can and must be channeled outwards, directed towards its real cause. Captured discontent. That is what the posting is. That is what the performed shock is. Real feeling, misdirected. Energy that could threaten something, redirected into a circuit that threatens nothing. The rage is genuine. The sorrow is genuine. But the channels into which they flow have been pre-dug, and the channels lead nowhere, and the energy dissipates harmlessly, and the system continues.</p>

      <p style={{ margin: "0 0 20px" }}>But who is going to channel it? Where is the lever? Fisher died in 2017, by his own hand, and the question he left us with remains unanswered. The conversion he called for has not happened. The captured discontent remains captured. And the system that produces the suffering continues to produce it, and we continue to post about it, and the posting continues to change nothing.</p>

      <p style={{ margin: "0 0 20px" }}>Now I have to return to where I started. I described a ritual of shock, a performance of confusion that has outlived any genuine confusion. But I need to be more precise about what I was actually seeing. It was not the shock. It was the satisfaction. The liberals I was describing are not trapped. They are comfortable. They have converted the captured discontent Fisher describes into something stable: identity, credential, belonging. The frustration Sontag names, compassion seeking action, they have found a way to short-circuit it. The performance is the action. The posting is the politics. The cage has become the house. They are not looking for the lever. They have stopped believing there should be one. The confusion is not a failure to understand. It is a refusal to act on what is understood. The how is this happening is not a question seeking an answer. It is a statement disguised as a question, a way of performing continued innocence, a method of staying shocked so that one never has to move past shock into the more difficult territory of response.</p>

      <p style={{ margin: "0 0 20px" }}>But not everyone in the feed has made that conversion. Some are still frustrated. Not performed frustration. Actual frustration, the kind that does not resolve. They post because silence feels like complicity, not because posting feels like action. They know the lever is missing. They have not stopped looking. The difference is not moral superiority. It is whether you have made peace with the trap.</p>

      <p style={{ margin: "0 0 20px" }}>[The discomfort of writing this is that I do not know which one I am. Some days I am looking for the lever. Some days I am just looking for the right way to describe the absence of the lever. Those are not the same thing. One of them might be its own kind of peace. The essay itself is suspicious. It allows me to feel that I am doing something, that the analysis is a form of action, that naming the trap is a step toward escaping it. But naming is not escaping. And sometimes the naming becomes a way of not escaping, a way of staying in the trap while feeling superior to those who do not know they are trapped. The critic's alibi. I see the cage, therefore I am not fully in it. But I am in it. I am writing from inside it. The keyboard is part of the cage.]</p>

      <p style={{ margin: "0 0 20px" }}>So: what would it look like to not make peace? I cannot name the lever. I do not have a program. But I can describe what I think I would recognize if I saw it. It would be uncomfortable. Not the discomfort of witnessing, which is passive and costs nothing. [But I am already suspicious of this. Describing the discomfort is not the same as feeling it. The conditional tense is doing a lot of work here, keeping everything hypothetical, safely in the realm of description. I could stop writing and go do something uncomfortable. I am not going to. I am going to keep describing.]</p>

      <p style={{ margin: "0 0 20px" }}>It would involve bodies. Flesh in rooms, in streets, in places where you cannot control the lighting or the frame. But even as I write this I notice that "bodies" has become a word people use in the feed, a way of signaling that you understand the stakes without actually putting your body anywhere. Bodies is a word that lets you keep sitting down.</p>

      <p style={{ margin: "0 0 20px" }}>It would be specific, I think. Not the ambient horror of everything, everywhere, all the time. A target. A pressure point. But specificity is also a trap, because choosing one thing means not choosing other things. And the feed punishes you for not choosing everything. The feed says: why are you focused on this when that is also happening? And you cannot answer, because the honest answer is: because I am one person, and one person cannot hold everything, and the choice to focus is the choice to let other things go. The feed does not permit that calculus. The feed demands you care about everything and act on nothing. [I am writing about specificity in the abstract. I have not named a single specific thing I am going to do. The abstraction is comfortable. The specific would be a commitment.]</p>

      <p style={{ margin: "0 0 20px" }}>It would risk something. Not the risk of being criticized online, which is just another form of engagement. Real risk. The kind that costs you something you actually valued. But what am I willing to lose? The honest answer is: not much. I want the feeling of commitment without the fact of it. I want the identity of resistance without the inconvenience. I am writing an essay about this, which is another way of not doing it.</p>

      <p style={{ margin: "0 0 20px" }}>It would be boring. Not the dopamine of outrage, the clean hit of sharing something terrible, the rush of being on the right side in real time. The long, tedious work of showing up again. Meetings that accomplish nothing. Phone calls to offices where no one answers. [But I am not going to those meetings. I am writing about the hypothetical virtue of going to those meetings. There is a genre of essay that describes the hard work and then stops, as if the description were the work. This might be that genre.] It would be local, rooted in the specific place where my body actually is. But I have not named the place. I have not named the people. I have kept it abstract because the abstract cannot fail. You cannot not show up to a meeting you never specified. You cannot abandon a community you never named.</p>

      <p style={{ margin: "0 0 20px" }}>It might not be legible as politics at all. It might look like care, or maintenance, or just refusing to leave. Showing up for people who cannot post about their own crises. Sitting with someone who is dying. Helping someone fill out a form. Doing the thing that needs doing, not because it will be seen, but because it needs doing. The feed has no category for this.</p>

      <p style={{ margin: "0 0 20px" }}>[I notice I have spent paragraphs describing what it would look like without committing to any of it. The conditional tense has infected everything. It would be. It would involve. It would risk. The would is a trapdoor. It lets me describe the escape without escaping. The essay ends and I am still here, having produced a document, having performed the critique of performance, having added one more thing to the feed. Someone might share it. Someone might say: this is exactly how I feel. And that would change nothing. And I would feel something anyway. And I do not know what to do with that.]</p>

      <p style={{ margin: "0 0 20px" }}>I do not know what it is. I do not have a manifesto. I am not calling for a movement. I am just trying to describe the texture of something that would feel different from this. Something that would convert the captured discontent into pressure rather than performance. Something that would take the frustration and give it somewhere to go that is not back into the loop. But I am still describing. Still framing. Still, in some sense, performing the critique of performance. And here I am, having written the essay.</p>

      <p style={{ margin: "0 0 20px" }}>[Or maybe that is just what I tell myself so I can finish the essay and close the laptop and feel like I did something today. The screen in the next room is still on. I can hear it from here. Someone is dying in the feed. Someone is always dying in the feed. And I am in the study, writing about it, which is another way of watching, which is another way of doing nothing, which is the only thing I know how to do.]</p>
    </div>
  );
}
